#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

if [ ! -f .env ]; then
  cp .env.example .env
  python3 - <<'PY'
from pathlib import Path
import secrets
p = Path('.env')
s = p.read_text()
s = s.replace('CHANGE_ME_POSTGRES', secrets.token_urlsafe(24))
s = s.replace('CHANGE_ME_JWT_SECRET', secrets.token_urlsafe(48))
# fernet key is generated by cryptography installed in the host only if available.
try:
    from cryptography.fernet import Fernet
    f = Fernet.generate_key().decode()
except Exception:
    f = 'CHANGE_ME_FERNET_KEY'
s = s.replace('CHANGE_ME_FERNET_KEY', f)
s = s.replace('sk-CHANGE_ME', '')
p.write_text(s)
PY
  echo "Created .env. Set LITELLM_MASTER_KEY to your current LiteLLM master key before continuing."
  exit 1
fi

docker compose up -d --build

echo
printf 'Portal: http://127.0.0.1:3100\n'
printf 'Health: '
curl -fsS http://127.0.0.1:3100 >/dev/null && echo OK || echo FAILED
printf '\nConnect cloudflared after verification:\n'
printf 'docker network connect hinaa_portal cloudflared 2>/dev/null || true\n'
printf 'Cloudflare route: panel.hinaa.ir -> http://hinaa-portal-frontend:3000\n'
