"""baseline existing production schema

Revision ID: 53ccaaff04df
Revises: 
Create Date: 2026-09-06 04:38:21.662458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '53ccaaff04df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
